INSERT INTO Body (Name, BodyID, Size, Type) VALUES ("lake evans", 1, 5892700, "lake");
INSERT INTO Body (Name, BodyID, Size, Type) VALUES ("castaic lake", 2, 430556, "lake");
INSERT INTO Body (Name, BodyID, Size, Type) VALUES ("pyramid lake", 3, 54892570, "lake");
INSERT INTO Body (Name, BodyID, Size, Type) VALUES ("quail lake", 4, 21527820, "lake");
INSERT INTO Body (Name, BodyID, Size, Type) VALUES ("lake isabella", 5, 617506560, "lake");
INSERT INTO Body (Name, BodyID, Size, Type) VALUES ("california aqueduct", 6, 257875200, "lake");
INSERT INTO Body (Name, BodyID, Size, Type) VALUES ("san luis ressivor", 7, 553107456, "ressivor");
INSERT INTO Body (Name, BodyID, Size, Type) VALUES ("oneill forebay", 8, 98020454, "lake");
INSERT INTO Body (Name, BodyID, Size, Type) VALUES ("lake webb", 9, 43462425, "lake");
INSERT INTO Body (Name, BodyID, Size, Type) VALUES ("lake ming", 10, 4530240, "lake");
